#:schema https://schema.wrangler.developers.cloudflare.com/config.json
name = "attendancetracker75"
compatibility_date = "2026-06-08"
compatibility_flags = [ "nodejs_compat" ]

[vars]
PUBLIC_ORIGIN = "http://localhost:4321"
